[project]
name = "website"
version = "0.1.0"
description = "Website made with Django"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django-debug-toolbar>=4.4.6",
    "django>=5.1.1",
]
